language: bash
sudo: required
dist: trusty
services:
    - docker
before_script:
    - echo 'before_script'
    - export AWS_REGION=eu-east-1
    - export TF_VAR_region=${AWS_REGION}
    - echo "using AWS_REGION=${AWS_REGION}"
    - export TF_WARN_OUTPUT_ERRORS=1
    - curl --silent --output terraform.zip https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip
    - sha256sum terraform.zip  | grep "c9a30d3e3abf751b3b3e323897e9c7cb411d5c4bb7473a3284a2a2b4b89f93ed"
    - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
    - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
    - terraform -v
script:
    - echo 'terraform validate and lint'
    - terraform init
    - terraform validate
    - docker run --rm -v $(pwd):/app/ --workdir=/app/ -t wata727/tflint
